#!/usr/bin/env bash
# .kiro/hooks/squad-guard.sh — preToolUse hook for file writes (Kiro) / PreToolUse for Write|Edit|MultiEdit|NotebookEdit (Claude Code).
# Enforces the document layout, role ownership, gate records, append-only ledgers and keeps secrets out of files:
#   * no file may receive a real-looking secret (cloud keys, tokens, private keys, webhook URLs);
#   * every write under docs/squad/ (and .kiro/rules/ or .claude/rules/ squad-learned-*) must be a path in
#     scripts/squad/layout.sh with a valid name — for everyone, so nothing is stored "somewhere";
#   * README.md and knowledge packs are generated by scripts, never written by hand;
#   * state.json, plan-approval.md, cab-approval.md: never written by a subagent (Delivery Manager only);
#   * decisions.md, errors.md, lessons.md, distill-log.md: append-only for everyone;
#   * squad-* subagents: may write only what their role owns (the layout's owner column, plus their code dirs).
# Needs jq; without jq it allows everything (and --doctor warns).
#
# Platform note. The role name is the first argument ($1), set in each squad-* agent's hook command (Kiro
# passes no agent_type/agent_id over stdin). On Claude Code the arg is absent and the role comes from .agent_type.
set -uo pipefail
command -v jq >/dev/null 2>&1 || exit 0
ROLE_ARG="${1:-}"
INPUT="$(cat)"
j() { printf '%s' "$INPUT" | jq -r "$1 // empty" 2>/dev/null; }

deny() {
  jq -n --arg r "squad-guard: $1" '{hookSpecificOutput:{hookEventName:"PreToolUse",permissionDecision:"deny",permissionDecisionReason:$r}}'
  exit 0
}

TOOL="$(j .tool_name)"
FILE="$(j .tool_input.file_path)"; [[ -z "$FILE" ]] && FILE="$(j .tool_input.notebook_path)"
[[ -z "$FILE" ]] && exit 0
# Role name is the first argument on Kiro (no agent_type/agent_id over stdin); fall back to .agent_type on Claude.
AGENT="${ROLE_ARG:-}"; [[ -z "$AGENT" ]] && AGENT="$(j .agent_type)"; AGENT="${AGENT##*:}"   # strip a plugin prefix such as "ecc:"
AGENT_ID="$(j .agent_id)"
# Kiro gives no agent_id; a squad-* role arg is the subagent signal there.
[[ -z "$AGENT_ID" && "$AGENT" == squad-* ]] && AGENT_ID="$AGENT"
CWD="$(j .cwd)"; [[ -z "$CWD" ]] && CWD="$PWD"

# The file's own checkout decides the root: a file inside a feature worktree belongs to that worktree, even when the
# session runs in the main checkout (and the other way round), as long as both are worktrees of the same repository.
gcd() { local c; c="$(git -C "$1" rev-parse --git-common-dir 2>/dev/null)" || return 0; (cd "$1" && cd "$c" && pwd -P); }
file_root() {
  local d; d="$(dirname "$1")"; while [[ ! -d "$d" && "$d" != / && "$d" != . ]]; do d="$(dirname "$d")"; done
  git -C "$d" rev-parse --show-toplevel 2>/dev/null || true
}
ROOT="$(git -C "$CWD" rev-parse --show-toplevel 2>/dev/null || true)"
[[ -z "$ROOT" ]] && ROOT="${CLAUDE_PROJECT_DIR:-$CWD}"
case "$FILE" in /*) ABS="$FILE" ;; *) ABS="$CWD/$FILE" ;; esac
FROOT="$(file_root "$ABS")"
if [[ -n "$FROOT" && "$FROOT" != "$ROOT" && "$(gcd "$FROOT")" == "$(gcd "$ROOT")" ]]; then ROOT="$FROOT"; fi
case "$ABS" in "$ROOT"/*) REL="${ABS#"$ROOT"/}" ;; *) exit 0 ;; esac   # outside the project: not ours

NEW_TEXT="$(printf '%s' "$INPUT" | jq -r '[.tool_input.content, .tool_input.new_string, (.tool_input.edits[]?.new_string)] | map(select(. != null)) | join("\n")' 2>/dev/null)"

# 0. Secrets never go into files (everyone, every path in the project).
SECRET='AKIA[0-9A-Z]{16}|-----BEGIN ([A-Z]+ )?PRIVATE KEY-----|gh[pousr]_[A-Za-z0-9]{36,}|xox[abprs]-[A-Za-z0-9-]{10,}|sk-(live|proj|ant)-[A-Za-z0-9_-]{20,}|hooks\.slack\.com/services/T[A-Z0-9]+/B[A-Z0-9]+/[A-Za-z0-9]+|AIza[0-9A-Za-z_-]{35}'
if printf '%s' "$NEW_TEXT" | grep -qE "$SECRET"; then
  deny "the content contains what looks like a real secret (API key, token, private key or webhook URL). Read it from the environment and document the variable name in .env.example instead."
fi

# 0b. state.json must stay valid (Delivery Manager writes it whole).
if [[ "$REL" == docs/squad/features/*/state.json && "$TOOL" == Write ]]; then
  printf '%s' "$NEW_TEXT" | jq -e 'type == "object" and has("feature") and has("stage") and has("tier") and has("loops") and has("gates") and has("history") and (.tier | IN("standard","large"))' >/dev/null 2>&1 \
    || deny "state.json must be valid JSON with feature, stage, tier (standard|large), loops, gates and history (see the /squad skill)."
fi

# 1. Document layout: classify the path with the single layout table.
LAYOUT="$ROOT/scripts/squad/layout.sh"; [[ -x "$LAYOUT" ]] || LAYOUT="${CLAUDE_PROJECT_DIR:-$ROOT}/scripts/squad/layout.sh"
KEY=""; OWNER=""; KIND=""
case "$REL" in
  docs/squad/*|.kiro/rules/squad-learned-*|.claude/rules/squad-learned-*)
    if [[ -x "$LAYOUT" ]]; then
      C="$(SQUAD_ROOT="$ROOT" "$LAYOUT" classify "$REL")"
      KEY="$(printf '%s' "$C" | cut -f1)"; OWNER="$(printf '%s' "$C" | cut -f2)"; KIND="$(printf '%s' "$C" | cut -f3)"
      [[ "$KEY" == UNKNOWN ]] && deny "$REL is not in the document layout: $OWNER. Use the path from scripts/squad/layout.sh table (or put evidence in features/<slug>/evidence/<stage>/<YYYYMMDD-HHMMSS>-<desc>.<ext>)."
    fi ;;
esac
case "$KIND" in
  generated) deny "$REL is generated (${OWNER}) — run the script instead of writing it by hand." ;;
  approval|state|baseline) [[ -n "$AGENT_ID" ]] && deny "$REL is written only by the Delivery Manager (main session), from the CEO's Gate-1 decision; report what you need in your HANDOFF (or an ADR-deviation)." ;;
esac

# 2. Append-only ledgers.
if [[ "$KIND" == ledger && -f "$ABS" ]]; then
  case "$TOOL" in
    Write)
      old="$(cat "$ABS")"; new="$(j .tool_input.content)"
      [[ "${new:0:${#old}}" == "$old" ]] || deny "$REL is append-only: keep every earlier entry unchanged and add the new one at the end." ;;
    Edit)
      o="$(j .tool_input.old_string)"; n="$(j .tool_input.new_string)"
      [[ -n "$o" && "${n:0:${#o}}" == "$o" ]] || deny "$REL is append-only: an edit may only add text after an existing anchor (new_string must start with old_string)." ;;
    MultiEdit)
      bad="$(printf '%s' "$INPUT" | jq -r '[.tool_input.edits[]? | select((.old_string|length)==0 or (.new_string|startswith(.old_string))|not)] | length' 2>/dev/null)"
      [[ "${bad:-1}" == "0" ]] || deny "$REL is append-only." ;;
  esac
fi

# 3. Ownership for squad role agents.
[[ "$AGENT" == squad-* ]] || exit 0
if [[ -n "$KEY" ]]; then
  case "$OWNER" in
    "any role"*) exit 0 ;;
    "$AGENT"|"$AGENT "*) exit 0 ;;
  esac
  deny "$AGENT may not write $REL — the layout gives it to '$OWNER'. Report the need in your HANDOFF (blocking / contract_issue) instead."
fi
CFG="$ROOT/.kiro/squad/config.env"; [[ -f "$CFG" ]] || CFG="$ROOT/.claude/squad/config.env"
cfg() { grep "^$1=" "$CFG" 2>/dev/null | head -1 | cut -d= -f2-; }
BE="$(cfg BACKEND_DIR)"; BE="${BE:-backend}"
FE="$(cfg FRONTEND_DIR)"; FE="${FE:-frontend}"
E2E="$(cfg E2E_DIR)"; E2E="${E2E:-e2e}"
case "$AGENT:$REL" in
  squad-backend:"$BE"/*|squad-frontend:"$FE"/*|squad-qa:"$E2E"/*) exit 0 ;;
  squad-sa:docs/adr/*) exit 0 ;;
  squad-release:scripts/squad/deploy.sh|squad-release:scripts/squad/smoke.sh|squad-release:scripts/squad/rollback.sh|squad-release:scripts/squad/pipeline.env) exit 0 ;;
esac
case "$AGENT" in
  squad-po|squad-researcher|squad-sa|squad-ba|squad-lead|squad-qa|squad-backend|squad-frontend|squad-reviewer|squad-release|squad-cto)
    deny "$AGENT may not write $REL — outside its role's files. Report the need in your HANDOFF instead." ;;
esac
exit 0
