"""T-066 / NFR-003 / ADR-0011 A3: recall of the server's HNSW search against brute force.

The corpus is generated by `scripts/recall_benchmark.py` and loaded THROUGH the ingest pipeline
(T-075); 50 queries from `eval/recall_queries.yaml`. The deterministic fake provider is used, so
this proves the index and the query path, not semantic quality: a real-model run is pending (it
needs the S2 model weights; see docs/signoff/phase-3.md). pgvector here may be < 0.8, in which case
the over-fetch fallback is the path under test; the iterative-scan path stays `@live`.
"""

from __future__ import annotations

import importlib.util
import sys
from pathlib import Path

import psycopg
import pytest
from mcp_ingest.embedding.fake import DeterministicFakeProvider

ROOT = Path(__file__).resolve().parents[3]
SCRIPT = ROOT / "scripts" / "recall_benchmark.py"
QUERIES = ROOT / "eval" / "recall_queries.yaml"


@pytest.fixture(scope="module")
def bench():
    spec = importlib.util.spec_from_file_location("recall_benchmark", SCRIPT)
    module = importlib.util.module_from_spec(spec)
    sys.modules["recall_benchmark"] = module
    spec.loader.exec_module(module)
    return module


def test_the_query_file_is_the_reproducible_output_of_the_generator(bench) -> None:
    queries = bench.load_queries(QUERIES)
    assert len(queries) == 50
    assert [q["text"] for q in queries] == [q["text"] for q in bench.synthetic_queries()]
    assert len({q["id"] for q in queries}) == 50


def test_load_queries_rejects_duplicates_and_empty_text(bench, tmp_path: Path) -> None:
    bad = tmp_path / "q.yaml"
    bad.write_text("queries:\n- {id: a, text: x}\n- {id: a, text: y}\n")
    with pytest.raises(ValueError):
        bench.load_queries(bad)


@pytest.fixture
def loaded_corpus(admin_dsn: str, rw_dsn: str, bench) -> int:
    chunks = bench.load_synthetic(rw_dsn, DeterministicFakeProvider(), per_topic=22)
    with psycopg.connect(admin_dsn, autocommit=True) as conn:  # the table owner may ANALYZE
        conn.execute("ANALYZE kb.chunks")
        conn.execute("ANALYZE kb.documents")
    return chunks


@pytest.mark.asyncio
async def test_NFR_003_recall_at_10_is_at_least_0_95_on_50_queries(
    bench, loaded_corpus: int, ro_dsn: str, pg_server
) -> None:
    assert loaded_corpus >= 1300  # a corpus big enough for HNSW to matter
    provider = DeterministicFakeProvider()
    queries = bench.load_queries(QUERIES)

    # the ground truth really is exact: it equals an independent ORDER BY over the whole table
    vector = provider.embed_query(queries[0]["text"])
    with psycopg.connect(ro_dsn, autocommit=True) as conn:
        exact = bench.brute_force_ids(conn, vector, provider.model_id, 10)
        independent = conn.execute(
            "SELECT id FROM kb.chunks ORDER BY embedding <=> %s::vector LIMIT 10",
            (bench._vector(vector),),
        ).fetchall()
    assert len(set(exact)) == 10 and {r[0] for r in independent} == set(exact)

    report = await bench.measure(ro_dsn, provider, queries, top_k=10)
    assert len(report.per_query) == 50
    assert report.index_used, "the planner must actually use HNSW, otherwise recall is trivially 1"
    assert report.mean >= 0.95, (report.as_dict(), pg_server.pgvector_version)


def test_NFR_001_mcp_query_ro_cannot_write_to_the_corpus(ro_dsn: str, seeded_ids) -> None:
    """FR-011/AC-003: every INSERT/UPDATE/DELETE through the server's role is refused."""
    statements = [
        "INSERT INTO kb.documents (source_type, source_id, source_uri, content_hash) "
        "VALUES ('x','y','https://x','h')",
        "UPDATE kb.documents SET title = 'hacked'",
        "DELETE FROM kb.chunks",
        "TRUNCATE kb.chunks",
        "DROP TABLE kb.chunks",
    ]
    with psycopg.connect(ro_dsn, autocommit=True) as conn:
        for sql in statements:
            with pytest.raises(psycopg.errors.Error):  # permission denied or read-only transaction
                conn.execute(sql)
    with psycopg.connect(ro_dsn, autocommit=True) as conn:
        assert conn.execute("SELECT count(*) FROM kb.chunks").fetchone()[0] > 0
